version: "3.8"
services:
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: hacking-metasploitable2
    tty: true
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.5
    expose:
      - "8180"
  dvwa:
    image: vulnerables/web-dvwa
    container_name: hacking-dvwa
    tty: true
    expose:
      - "80"
  bwapp:
    image: raesene/bwapp
    container_name: hacking-bwapp
    tty: true
    expose:
      - "80"
  kali:
    container_name: hacking-kali-linux
    build: ./docker/kali
    tty: true
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.2
    expose:
      - "5555"
      - "4444"
    # volumes:
    #   - ./work:/root
    # 今のところ保持しておきたいものないしいらないかな。
  nginx:
    container_name: hacking-nginx
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./work:/usr/share/nginx/html
networks:
  hacking-lab:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
    # external: true # これつけるとここで定義してるコンテナ以外でも他のdocker-compose.ymlで定義したコンテナと通信できるって感じっぽい。

    # https://zaki-hmkc.hatenablog.com/entry/2021/02/26/234357
    # ipアドレスの指定とサブネットの指定方法
