version: "3.8"
services:
  kali:
    container_name: hacking-kali-linux
    build: ./docker/kali
    tty: true
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.2
    expose:
      - "5555"
      - "4444"
    volumes:
      - ./hacking-lab:/root/hacking-lab
      - ./docker/kali/config/samba/smb.conf:/etc/samba/smb.conf
    # 今のところ保持しておきたいものないしいらないかな。
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: hacking-metasploitable2
    tty: true
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.5
    ports:
      - "8180:8180" # ホスト：コンテナで二つ指定してないとホスト側のポートは適当なポートになる。
  dvwa:
    image: vulnerables/web-dvwa
    container_name: hacking-dvwa
    tty: true
    expose:
      - "80"
  bwapp:
    image: raesene/bwapp
    container_name: hacking-bwapp
    tty: true
    expose:
      - "80"
  nginx:
    container_name: hacking-nginx
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./work:/usr/share/nginx/html
networks:
  hacking-lab:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
    # external: true # これつけるとここで定義してるコンテナ以外でも他のdocker-compose.ymlで定義したコンテナと通信できるって感じっぽい。

    # https://zaki-hmkc.hatenablog.com/entry/2021/02/26/234357
    # ipアドレスの指定とサブネットの指定方法
    # ハッキングラボにあるnat環境は別にたてなくていいと思う。
    # dockerの機能でnat機能持った状態になってるので特に何もしなくてもどのコンテナでもちゃんとインターネットに通信できる。
    # ハッキングラボの環境だとvmマシンないからでも検索できるつまりインターネットを利用できるようにしたいてのがあってnatを使ってなくてもなんか通信できる。
    # よくわからんけど多分ここら辺はdockerがiptableみたいなのを作ってやってくれてる？
    # だからnatを使って通信できるようにしなくても別にいいって感じかな。natって何やっけ？確かプライベートipをglobalなipに変換するとかやっけ？
    # まぁVMのホストオンリーネットワークにkaliとかmetasploitとか入れてるけどこいつらはホストOSからしか通信できないようにしてるからセキュアってだけ。でkaliだけインターネットにつなげるためにnatを使用してる。
    # dockerやとここら辺セキュアになってるんかな？metasploitとかにはアクセスできないって理解でいいんやろか？あれやったらネット使えないように設定すればいいのかな？
    # https://qiita.com/kenchan1193/items/b65256c78988e1a87526 やっぱnat使われてそう？
    # あーでもports: 8080とかやと確か、ネットワークにポート見えるんやったな。そうなるとこのpcのlistenしてるポート見られたら見れてしまう。
    # というかec2とかでサーバーを立ててglobalipを取得するのってなんで危ないの？家のwifiでdocker立てるのと何が違うのか？globalなところからlocalのipアドレスを割り当ててるからルーターの時点ではじいてくれてる？
    # ここら辺よくわからない。インターネットからしてみたら、俺らのlan内は見えない。（正確にはどうなのか知らんけどfirewallではじいてるやろ）けどglobal ipは見える。インターネットに出てるから。
    # つまり俺の上のルーター部分のソフトバンクのipルーターに関しては見えてるってことかな？
    # だからec2とか立てて、ルーティング設定してデフォルトゲートウェイ設定してwebを向くようにしているwebとかだと、他にもlistenしてるポートを見られるとやばい？そもそも見れるのか知らんけど多分ipアドレスが見れればlistenしてるポートはnmapとかでスキャンすればわかるはず。こうなると80とか443とかはどうやってアクセスしてる？これはdns（route53とかってdnsなんかな？）でやってたっけ？とりあえずhttpとかhttpsでリクエストしたら自動で80か443になるんか、名前解決の時点でそうなってるんか知らんけど、どっかでそうやってポート指定してリクエストしてるはず。この時にdockerのportsで設定してるとホストのポートをフォワーディングしてるからnmapで出てきてホスト外のやつにも見えてしまうみたいな感じやったはず(わからんけど）。
    # https://knowledge.sakura.ad.jp/23899/ ここら辺呼んでdockerのネットワーク理解しとけ。
    # けど家のlan内ならそこまで考えなくてもlan内で立てたコンテナにインターネットからアクセスはできないんじゃないのかな？って思う。
    # https://teratail.com/questions/74946 dockerでポートだけ公開して外部には公開しないようにするには？
    #
    # まぁいったんportはホスト側からアクセスしたいみたいなwebとかの時は使うけど別にホストからアクセスする必要なくてコンテナ同士で通信するだけならexposeでいいかな。
