version: "3.8"
services:
  kali:
    container_name: hacking-kali-linux
    build: ./docker/kali
    tty: true
    # /bin/bashで起動するとsystemctlが使えない
    # privileged: trueと/sbin/initで起動すると使えるみたい。
    # けど確かprivilegedって特権モードみたいな感じだった気がするからあんまりよくない気もする。
    # なんでもできないようにsystemctlも操作できないとか？dockerの部分まで触れるようになるとかなんやろか？知らんけど
    # https://qiita.com/niwasawa/items/85a78aaa8c5234d98fb4
    privileged: true
    command: /bin/bash
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.2
    expose:
      - "5555"
      - "4444"
    ports:
      - "8888:80"
      - "3390:3389" # xrdp
    volumes:
      - ./hacking-lab:/root/hacking-lab
      - ./docker/kali/config/samba/smb.conf:/etc/samba/smb.conf
      - ./docker/kali/config/html:/var/www/html
  metasploitable:
    image: tleemcjr/metasploitable2
    container_name: hacking-metasploitable2
    tty: true
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.5
    ports:
      - "8180:8180" # ホスト：コンテナで二つ指定してないとホスト側のポートは適当なポートになる。
  dvwa:
    image: vulnerables/web-dvwa
    container_name: hacking-dvwa
    tty: true
    ports:
      - "3333:80"
  bwapp:
    image: raesene/bwapp
    container_name: hacking-bwapp
    networks:
      hacking-lab:
        ipv4_address: 10.0.0.103
    tty: true
    ports:
      - "2222:80"
  nginx:
    container_name: hacking-nginx
    image: nginx:latest
    expose:
      - "80"
    volumes:
      - ./work:/usr/share/nginx/html
networks:
  hacking-lab:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
